# Generated by Django 4.2.1 on 2023-05-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.CharField(max_length=250, unique_for_date="publish"),
        ),
    ]
